spring:
  application:
    name: product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka

server:
  port: 8082
---
spring:
  profiles: DEV

  datasource:
    url: jdbc:mysql://localhost:3306/strabl
    username: root
    password: ___patidar@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  httpclient:
    enabled: true

cloud:
  aws:
    region:
      static: eu-west-1
      auto: false

data:
  redis:
    host: localhost
    port: 6379
---
spring:
  profiles: PROD

  datasource:
    url: jdbc:mysql://strabl-test-db-free.cfqariljdlrh.ap-south-1.rds.amazonaws.com:3306/strabl
    username: admin
    password: strabl123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  httpclient:
    enabled: true

cloud:
  aws:
    region:
      static: ap-south-1
      auto: false

data:
  redis:
    host: strabl-test-redis-1.wyt7yq.0001.aps1.cache.amazonaws.com
    port: 6379
---
